name: report-exporter

version: 1.1.0

port: 8080

service:
  port: 8080

ingress:
  required: true
  site: report-exporter

image:
  name: report-exporter
  version: latest

monitoring:
  namespace: openshift-monitoring
  prometheusScrapePath: /actuator/prometheus
  jobLabel: app

dockerProxyRegistry: nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com
