apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.role.name }}
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: report-exporter
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.role.name }}
  apiGroup: rbac.authorization.k8s.io
